all:
  hosts:
    master-1:
      ansible_host: 158.160.113.16
      ip: 10.0.1.27
      access_ip: 158.160.113.16
    master-2:
      ansible_host: 158.160.33.223
      ip: 10.0.1.35
      access_ip: 158.160.33.223
    master-3:
      ansible_host: 158.160.42.247
      ip: 10.0.1.12
      access_ip: 158.160.42.247
  children:
    kube_control_plane:
      hosts:
        master-1:
        master-2:
        master-3: